version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "daily"
      time: "11:15"
      timezone: "America/Sao_Paulo"

    target-branch: "develop"

    commit-message:
      prefix: "chore"
      include: "scope"

    labels:
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/"

    schedule:
      interval: "daily"
      time: "11:15"
      timezone: "America/Sao_Paulo"

    target-branch: "develop"

    commit-message:
      prefix: "chore"
      include: "scope"

    labels:
      - "dependencies"
