version: 2
updates:  
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
